name: gain
description: Une app de muscu et nutrition premium.
publish_to: 'none'

version: 1.2.2+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2       # Pour prendre des photos avec l'appareil ou la galerie
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  percent_indicator: ^4.2.5
  shared_preferences: ^2.3.2
  mobile_scanner: ^7.2.0
  font_awesome_flutter: ^11.0.0
  supabase_flutter: ^2.8.0
  fl_chart: ^1.2.0           # Mis à jour pour SPM
  intl: ^0.20.2              # Mis à jour pour SPM
  file_picker: ^8.3.7        # Mis à jour pour forcer la compatibilité iOS 14+
  app_links: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # 🛠️ AJOUT : Le package de génération d'icônes

# 🎯 CONFIGURATION DE TON ICÔNE GAIN
flutter_launcher_icons:
  image_path: "assets/img/logo.png" # 🖼️ On utilise ton logo existant
  ios: true
  android: true

flutter:
  uses-material-design: true

  # 🖼️ Section Assets correctement isolée et alignée sous la racine "flutter:"
  assets:
    - assets/img/logo.png
    - assets/img/min_logo.png
    - assets/img/logo_trans.png
    - assets/img/min_logo_trans.png