name: liftlog
description: Une app de muscu et nutrition.
publish_to: 'none'

version: 1.0.1+7

environment:
  sdk: '>=3.0.0 <4.0.0' # Version standard pour accepter les packages récents

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  percent_indicator: ^4.2.5
  shared_preferences: ^2.3.2
  mobile_scanner: ^7.2.0
  font_awesome_flutter: ^11.0.0
  supabase_flutter: ^2.8.0
  fl_chart: ^1.2.0      # Mis à jour pour SPM
  intl: ^0.20.2         # Mis à jour pour SPM
  file_picker: ^12.0.0  # Mis à jour pour forcer la compatibilité iOS 14+

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Mis à jour

flutter:
  uses-material-design: true